ignoreGeneratedHeader = false
severity = "warning"
confidence = 0.8
warningCode = 1

[rule.atomic]
[rule.blank-imports]
[rule.comment-spacings]
  arguments = ["lint", "goland"]
[rule.context-as-argument]
[rule.context-keys-type]
[rule.datarace]
[rule.defer]
[rule.dot-imports]
  exclude = ["**/*_test.go"]
[rule.duplicated-imports]
[rule.empty-block]
[rule.error-return]
[rule.error-strings]
[rule.error-naming]
[rule.errorf]
[rule.exported]
[rule.identical-branches]
[rule.import-alias-naming]
[rule.increment-decrement]
[rule.indent-error-flow]
[rule.optimize-operands-order]
[rule.range]
[rule.range-val-in-closure]
[rule.range-val-address]
[rule.receiver-naming]
[rule.redundant-import-alias]
[rule.superfluous-else]
[rule.unexported-naming]
[rule.unexported-return]
[rule.unreachable-code]
[rule.useless-break]
[rule.var-declaration]
[rule.var-naming]
[rule.waitgroup-by-value]
